# Generated by Django 5.1.7 on 2025-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("turismo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cluster",
            field=models.IntegerField(default=999),
        ),
    ]
