# Generated by Django 5.1.7 on 2025-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_reservahotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
