# Generated by Django 5.1.7 on 2025-04-01 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0004_alter_ruta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenpoints',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='no description', max_length=200),
            preserve_default=False,
        ),
    ]
