# Generated by Django 5.1.7 on 2025-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0005_greenpoints_usuario_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinionhotel',
            name='palabras_clave',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opinionruta',
            name='palabras_clave',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opinionservicio',
            name='palabras_clave',
            field=models.JSONField(default=list),
        ),
    ]
