# Generated by Django 5.1.7 on 2025-04-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0006_opinionhotel_palabras_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opinionhotel',
            name='palabras_clave',
        ),
        migrations.RemoveField(
            model_name='opinionruta',
            name='palabras_clave',
        ),
        migrations.RemoveField(
            model_name='opinionservicio',
            name='palabras_clave',
        ),
        migrations.AddField(
            model_name='hotel',
            name='descripcion',
            field=models.CharField(default='No hay descripcion algo no va bien...', max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='foto',
            field=models.CharField(default='Aún no hay foto', max_length=200),
        ),
        migrations.AddField(
            model_name='opinionhotel',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinionruta',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinionservicio',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
