# Generated by Django 5.1.7 on 2025-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0007_remove_hotel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='ruta_popular',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipo_transporte',
            field=models.CharField(max_length=50),
        ),
    ]
