# Generated by Django 5.1.7 on 2025-04-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0008_alter_transporte_ruta_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='marketing_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turismo.hotel')),
            ],
        ),
    ]
