# Generated by Django 5.1.7 on 2025-04-05 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0009_marketingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingimage',
            name='image',
            field=models.ImageField(upload_to='images/marketing_images/'),
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(default=999)),
                ('recomendaciones', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
